// <auto-generated />
using Equipment.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Equipment.Persistence.Migrations
{
    [DbContext(typeof(EquipmentDBContext))]
    [Migration("20250324115759_Initial3")]
    partial class Initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.ConcentrationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComponentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FilterPortEntityId")
                        .HasColumnType("bigint");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("FilterPortEntityId");

                    b.ToTable("ConcentrationEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.DiametrEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DiametrEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.DistributionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComponentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FilterPortEntityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("FilterPortEntityId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.EquipmentTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.MaterialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsNonСorrosive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.PipeTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PipeTypeEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.StageTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompanyEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyEntityId");

                    b.ToTable("StageTypes");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.CompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ComponentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Charge")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentState")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCounterIon")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReagent")
                        .HasColumnType("boolean");

                    b.Property<double>("MaxConcntration")
                        .HasColumnType("double precision");

                    b.Property<double>("MollMass")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ExternalProgrammsInfos.ExternalProgrammsInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EplanId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RevitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EplanId");

                    b.HasIndex("RevitId");

                    b.ToTable("ExternalProgrammsInfos");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Eplan.EplanBlockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Articles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmaMacroPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmvMacroPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Hash")
                        .HasColumnType("double precision");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("InsertionPointRel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepresentationType")
                        .HasColumnType("integer");

                    b.Property<string>("TopLeftRel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("EplanBlocks");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Eplan.EplanPortEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EplainBlockId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PipeTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("PortSide")
                        .HasColumnType("integer");

                    b.Property<string>("PositionRel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EplainBlockId");

                    b.HasIndex("PipeTypeId");

                    b.ToTable("EplanPortEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Revit.RevitBlockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FamilyFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Hash")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("RevitBlockEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.Port", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DiametrId")
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortNumber")
                        .HasColumnType("integer");

                    b.Property<double>("Pressure")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiametrId");

                    b.ToTable("Ports");

                    b.HasDiscriminator().HasValue("Port");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.FilterUnitEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EquipmentTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("StageTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.InlineUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code1C")
                        .HasColumnType("text");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RArticle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MaterialId");

                    b.ToTable("InlineUnit");

                    b.HasDiscriminator().HasValue("InlineUnit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.SpecificFilterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code1C")
                        .HasColumnType("text");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ExternalProgrammsInfoId")
                        .HasColumnType("bigint");

                    b.Property<long>("FilterUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RArticle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WaterflowMax")
                        .HasColumnType("double precision");

                    b.Property<double>("WaterflowMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExternalProgrammsInfoId");

                    b.HasIndex("FilterUnitId");

                    b.HasIndex("MaterialId");

                    b.ToTable("SpecificFilters");
                });

            modelBuilder.Entity("EquipmentPortInlineUnit", b =>
                {
                    b.Property<long>("InlineUnitsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PorstsAttachedToId")
                        .HasColumnType("bigint");

                    b.HasKey("InlineUnitsId", "PorstsAttachedToId");

                    b.HasIndex("PorstsAttachedToId");

                    b.ToTable("EquipmentPortInlineUnit");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.CommonInlinePort", b =>
                {
                    b.HasBaseType("Equipment.Domain.Entities.Ports.Port");

                    b.Property<long>("CommonInlineUnitId")
                        .HasColumnType("bigint");

                    b.HasIndex("CommonInlineUnitId");

                    b.HasDiscriminator().HasValue("CommonInlinePort");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.EquipmentPort", b =>
                {
                    b.HasBaseType("Equipment.Domain.Entities.Ports.Port");

                    b.Property<long>("PipeTypeId")
                        .HasColumnType("bigint");

                    b.HasIndex("PipeTypeId");

                    b.HasDiscriminator().HasValue("EquipmentPort");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.PumpInlinePort", b =>
                {
                    b.HasBaseType("Equipment.Domain.Entities.Ports.Port");

                    b.Property<long>("PumpUnitId")
                        .HasColumnType("bigint");

                    b.HasIndex("PumpUnitId");

                    b.HasDiscriminator().HasValue("PumpInlinePort");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.CommonInlineUnitEntity", b =>
                {
                    b.HasBaseType("Equipment.Domain.Entities.Units.InlineUnit");

                    b.HasDiscriminator().HasValue("CommonInlineUnitEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.PumpInlineUnitEntity", b =>
                {
                    b.HasBaseType("Equipment.Domain.Entities.Units.InlineUnit");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("PumpInlineUnitEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.FilterPortEntity", b =>
                {
                    b.HasBaseType("Equipment.Domain.Entities.Ports.EquipmentPort");

                    b.Property<long>("FilterUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("FilterUnitId");

                    b.HasDiscriminator().HasValue("FilterPortEntity");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.ConcentrationEntity", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.ComponentEntity", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Ports.FilterPortEntity", null)
                        .WithMany("PDK")
                        .HasForeignKey("FilterPortEntityId");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.DistributionEntity", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.ComponentEntity", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Ports.FilterPortEntity", null)
                        .WithMany("Distributions")
                        .HasForeignKey("FilterPortEntityId");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Commons.StageTypeEntity", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.CompanyEntity", null)
                        .WithMany("Stage")
                        .HasForeignKey("CompanyEntityId");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ExternalProgrammsInfos.ExternalProgrammsInfo", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Eplan.EplanBlockEntity", "Eplan")
                        .WithMany()
                        .HasForeignKey("EplanId");

                    b.HasOne("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Revit.RevitBlockEntity", "Revit")
                        .WithMany()
                        .HasForeignKey("RevitId");

                    b.Navigation("Eplan");

                    b.Navigation("Revit");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Eplan.EplanPortEntity", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Eplan.EplanBlockEntity", "EplainBlock")
                        .WithMany("Ports")
                        .HasForeignKey("EplainBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Commons.PipeTypeEntity", "PipeType")
                        .WithMany()
                        .HasForeignKey("PipeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EplainBlock");

                    b.Navigation("PipeType");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.Port", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.Commons.DiametrEntity", "Diametr")
                        .WithMany()
                        .HasForeignKey("DiametrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diametr");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.FilterUnitEntity", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.Commons.EquipmentTypeEntity", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Commons.StageTypeEntity", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.InlineUnit", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Commons.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.SpecificFilterEntity", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.ExternalProgrammsInfos.ExternalProgrammsInfo", "ExternalProgrammsInfo")
                        .WithMany()
                        .HasForeignKey("ExternalProgrammsInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Units.FilterUnitEntity", "FilterUnit")
                        .WithMany("AttachedTo")
                        .HasForeignKey("FilterUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Commons.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ExternalProgrammsInfo");

                    b.Navigation("FilterUnit");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("EquipmentPortInlineUnit", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.Units.InlineUnit", null)
                        .WithMany()
                        .HasForeignKey("InlineUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment.Domain.Entities.Ports.EquipmentPort", null)
                        .WithMany()
                        .HasForeignKey("PorstsAttachedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.CommonInlinePort", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.Units.CommonInlineUnitEntity", "CommonInlineUnit")
                        .WithMany("Ports")
                        .HasForeignKey("CommonInlineUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonInlineUnit");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.EquipmentPort", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.Commons.PipeTypeEntity", "PipeType")
                        .WithMany()
                        .HasForeignKey("PipeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipeType");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.PumpInlinePort", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.Units.PumpInlineUnitEntity", "PumpUnit")
                        .WithMany("PumpPorts")
                        .HasForeignKey("PumpUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PumpUnit");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.FilterPortEntity", b =>
                {
                    b.HasOne("Equipment.Domain.Entities.Units.FilterUnitEntity", "FilterUnit")
                        .WithMany("Ports")
                        .HasForeignKey("FilterUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterUnit");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.CompanyEntity", b =>
                {
                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.ExternalProgrammsInfos.Fields.Eplan.EplanBlockEntity", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.FilterUnitEntity", b =>
                {
                    b.Navigation("AttachedTo");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.CommonInlineUnitEntity", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Units.PumpInlineUnitEntity", b =>
                {
                    b.Navigation("PumpPorts");
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Ports.FilterPortEntity", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("PDK");
                });
#pragma warning restore 612, 618
        }
    }
}
